name: Publish

on:
  push:
  schedule:
    # Auto-Update on Fridays
    - cron: 0 1 * * FRI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            _opam 
            _build
          key: 2

      - name: Apt Install Opam
        run: sudo apt install opam && opam init

      - name: Prepare
        run: ./run.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          cname: bonsai.red
