name: Publish

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - 4.12.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            _opam 
            _build
        key: 1

      - name: Apt Install Opam
        run: sudo apt install opam && opam init

      - name: Prepare
        run: ./run.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
